# Generated by Django 4.2.1 on 2023-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmod1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('num', models.IntegerField()),
                ('em', models.EmailField(max_length=254)),
                ('im', models.FileField(upload_to='diaryapp/static')),
                ('pin', models.CharField(max_length=30)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
