# Generated by Django 4.2.1 on 2023-09-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmod1',
            name='balance',
        ),
    ]
