# Generated by Django 4.2.1 on 2023-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_remove_regmod1_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='logmod1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('pswd', models.CharField(max_length=30)),
            ],
        ),
    ]
