# Generated by Django 4.2.1 on 2023-09-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0005_admnnewsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('newsid', models.IntegerField()),
                ('topic', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=3000)),
                ('date', models.DateField()),
            ],
        ),
    ]
