# Generated by Django 4.2.1 on 2023-09-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='newsid',
            new_name='admnnewsid',
        ),
    ]
